# 파일 다루기
- 파일 열기 open(), with로 열기
- csv, xlsx 파일 다루기
- zip 파일 다루기
- 폴더 내 파일 목록 다루기 (glob, listdir)
- 폴더/파일 생성과 삭제

## import

In [20]:
import pandas as pd
import numpy as np
from numpy.random import rand
import zipfile
import csv
import os
from glob import glob

##  데이터  생성과 저장하기
- 숫자 데이터를 생성하고 csv 파일로 저장하기

In [21]:
## 0~1 사이의 랜덤 넘버 10개를 만들고 csv 파일에 저장하고 확인하기
# 텍스트 파일 저장을 위해 savetxt()를 사용한다
# 소수점 몇 째 자리까지 저장할지를 정해주어야 한다 (텍스트로 표현되는)

import numpy as np
x1 = np.random.rand(10)
# print(type(x1))         # ndarray 타입

np.savetxt("test_1.csv", x1, delimiter=",", fmt = '%.3f')

with open('test_1.csv') as f: 
    contents = f.read()
    print(type(contents))  # str 타입
    print(contents)

<class 'str'>
0.970
0.856
0.034
0.167
0.252
0.415
0.726
0.456
0.224
0.104



In [22]:
## csv 파일을 어레이로 읽어서 1000을 곱한 값 보기
# 텍스트 파일을 loadtxt()로 읽으면 어레이로 읽는다 

x = np.loadtxt('test_1.csv', delimiter=',')
print(type(x))    # ndarray 타입
print(x*1000)

<class 'numpy.ndarray'>
[970. 856.  34. 167. 252. 415. 726. 456. 224. 104.]


### 2차원 구조 csv 데이터
- 행이 바뀔 때 리턴 코드가 들어 있다

In [23]:
## 0~30 로 구성된 (5,6) 구조의 어레이를 csv 파일에 저장하기

x2 = np.arange(30).reshape(5,6)

np.savetxt("test_2.csv", x2, delimiter=",", fmt = '%d')

with open('test_2.csv') as f: 
    contents = f.read()
    print(type(contents))  # str 타입
    print(contents)

<class 'str'>
0,1,2,3,4,5
6,7,8,9,10,11
12,13,14,15,16,17
18,19,20,21,22,23
24,25,26,27,28,29



In [24]:
## 2차원 csv 파일을 어레이로 읽는 예

x = np.loadtxt('test_2.csv', delimiter=',')
print(type(x))
print(x)

<class 'numpy.ndarray'>
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]]


## 데이터프레임으로 읽기

In [25]:
## 2차원 어레이를 데이터프레임으로 읽기

df = pd.read_csv('test_2.csv')  
df

,0,1,2,3,4,5
0,6,7,8,9,10,11
1,12,13,14,15,16,17
2,18,19,20,21,22,23
3,24,25,26,27,28,29


In [26]:
# 어레이로 변환하기
df.values

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### 액셀 한글 인코딩
- 문자의 인코딩은 기본적으로 utf-8 을 사용한다
- 그러나 한글의 경우 다른 인코딩으로 저장되는 경우가 있다
 - MS 액셀에서 csv로 저장할 때 한글이 cpc949로 인코딩된다. 이때는 아래 옵션이 필요하다
 - encoding = 'cpc949'
 - encoding = 'euc-kr'을 선택해야 하는 경우도 있다

## 폴더의 파일 목록 얻기
- glob() 사용: 파일 타입을 편리하게 지정할 수 있다
- listdir() 사용: 경로를 지정할 수 있다

## glob() 사용

In [27]:
## 현재 폴더의 파일 목록 얻기

from glob import glob
f_list = glob('*.ipynb')
f_list

['i_09_clustering.ipynb',
 'e_56_DT_RF_Boost_Life.ipynb',
 'j_13_DT_RF_Boost_Titanic.ipynb',
 'f_21_StatisticsBasic.ipynb',
 'e_72_CatDog_Keras.ipynb',
 'e_22_Python.ipynb',
 'j_32_YOLOv8_Aquarium_Data_PC.ipynb',
 'j_01_Python.ipynb',
 'f_60_Surprise.ipynb',
 'e_62_Clustering.ipynb',
 'ee_87_1_TextAnalysis.ipynb',
 'e_61_PCA.ipynb',
 'e_42_Preprocessing_Example.ipynb',
 'e_75_1_YOLOv8_run_PC-Copy1.ipynb',
 'f_53_CustomerSegmentation.ipynb',
 'j_17_Add_features.ipynb',
 'e_25_Function.ipynb',
 'j_03_Numpy.ipynb',
 'j_10_Regression.ipynb',
 'e_23_Pandas.ipynb',
 'e_75_1_YOLOv8_run_1.ipynb',
 'e_24_numpy.ipynb',
 'j_19_DeepLearning.ipynb',
 'f_56_CreditcardFraudDetection.ipynb',
 'e_85_prophet.ipynb',
 'j_28_YOLOv8_run.ipynb',
 'e_75_1_YOLOv8_run.ipynb',
 'j_27_PM.ipynb',
 'i_01_MolRepresentation.ipynb',
 'z8_Autoencoders.ipynb',
 'j_05_FileFolder.ipynb',
 'e_32_Graphs.ipynb',
 'j_08_Preprocessing_Example.ipynb',
 'ee_81_2_Series_Shift.ipynb',
 'e_82_TimeSeries_XY_bike.ipynb',
 'j_14_DT_R

In [28]:
# 알파벳 순으로 리스트를 소팅한 결과 보기
# 파일의 순서를 통일시킬 때 필요하다

sorted(f_list)

['JupyterAI_Example.ipynb',
 'e_22_Python.ipynb',
 'e_23_1_GroupbyPractice.ipynb',
 'e_23_Pandas.ipynb',
 'e_24_numpy.ipynb',
 'e_25_Function.ipynb',
 'e_31_FileFolder.ipynb',
 'e_32_Graphs.ipynb',
 'e_41_Preprocessing.ipynb',
 'e_42_Preprocessing_Example.ipynb',
 'e_51_ML_Intro.ipynb',
 'e_52_Regression.ipynb',
 'e_53_Classification_OLD.ipynb',
 'e_53_Classification_new.ipynb',
 'e_54_LogisticRegression.ipynb',
 'e_56_DT_RF_Boost_Life.ipynb',
 'e_60_SVM.ipynb',
 'e_61_PCA.ipynb',
 'e_62_Clustering.ipynb',
 'e_63_Add_features.ipynb',
 'e_71_MLP_CNN_MNIST_Keras.ipynb',
 'e_72_CatDog_Keras.ipynb',
 'e_73_TransferLearning.ipynb',
 'e_74_ActivityRecognition.ipynb',
 'e_75_1_YOLOv8_run.ipynb',
 'e_75_1_YOLOv8_run_1.ipynb',
 'e_75_1_YOLOv8_run_PC-Copy1.ipynb',
 'e_75_1_YOLOv8_run_PC.ipynb',
 'e_75_2_YOLOv8_Aquarium_Data.ipynb',
 'e_75_2_YOLOv8_Aquarium_Data_PC.ipynb',
 'e_76_1_opencv_face.ipynb',
 'e_76_2_contour_detect.ipynb',
 'e_76_3_opencv_digit.ipynb',
 'e_77_ocr_PC.ipynb',
 'e_81_Times

## listdir() 사용
- 인자에 파일을 찾을 폴더 경로를 지정할 수 있다
- 쓰지 않으면 현재 폴더를 찾는다, 모든 파일을 찾아준다

In [29]:
os.listdir()

['i_09_clustering.ipynb',
 'e_56_DT_RF_Boost_Life.ipynb',
 'j_13_DT_RF_Boost_Titanic.ipynb',
 'cities.xlsx',
 'f_21_StatisticsBasic.ipynb',
 'test_1.csv',
 'e_72_CatDog_Keras.ipynb',
 'e_22_Python.ipynb',
 'j_32_YOLOv8_Aquarium_Data_PC.ipynb',
 'j_01_Python.ipynb',
 'f_60_Surprise.ipynb',
 'e_62_Clustering.ipynb',
 'ee_87_1_TextAnalysis.ipynb',
 'e_61_PCA.ipynb',
 'test_2.csv',
 'e_42_Preprocessing_Example.ipynb',
 'e_75_1_YOLOv8_run_PC-Copy1.ipynb',
 'f_53_CustomerSegmentation.ipynb',
 'j_17_Add_features.ipynb',
 'e_25_Function.ipynb',
 'j_03_Numpy.ipynb',
 'j_10_Regression.ipynb',
 'e_23_Pandas.ipynb',
 '.DS_Store',
 'e_75_1_YOLOv8_run_1.ipynb',
 'e_24_numpy.ipynb',
 'j_19_DeepLearning.ipynb',
 'f_56_CreditcardFraudDetection.ipynb',
 'e_85_prophet.ipynb',
 'j_28_YOLOv8_run.ipynb',
 'e_75_1_YOLOv8_run.ipynb',
 'j_27_PM.ipynb',
 'i_01_MolRepresentation.ipynb',
 'z8_Autoencoders.ipynb',
 'j_05_FileFolder.ipynb',
 'e_32_Graphs.ipynb',
 'j_08_Preprocessing_Example.ipynb',
 'ee_81_2_Series

## 기타 폴더 및 파일 관리 함수
- os 패키지에서 제공하는 함수
 - 폴더 생성 mkdir()
 - 폴더 위치 이동 chdir()
 - 파일 이름 변경 rename()
 - 파일 삭제 remove()
 - 폴더 삭제 rmdir()